### ISSUE TITLE
Ability to disable debug log output

### ISSUE THREAD

**Issue by altishchenko** [amperka/TroykaMQ#1]
Please, provide the ability to disable serial debug output from BaseMQ.cpp
Serial.println("Heated sensor");
Serial.println("Cool sensor");

Пожалуйста, предоставьте возможность отключать консольные сообщения от BaseMQ.cpp, хотя бы через #ifdef DEBUG.

**Comment by nkrkv** [comment]
@Igor89 обрати внимание, пожалуйста, и пофикси. Библиотека не должна сыпать в Serial по умолчанию.

**Comment by nomad605dis** [comment]
All fixed.
