### ISSUE TITLE
How did you find the coefficients to read Carbon Monoxide in MQ9?

### ISSUE THREAD

**Issue by glundgren93** [amperka/TroykaMQ#6]
unsigned long MQ9::readCarbonMonoxide() {
  return readScaled(-0.48, 3.10);
}

How did you manage to get these values (-0.48, 3.10)?

**Comment by nomad605dis** [comment]
Hi!

We used the value of PPM and RS / RO from the datasheet to the MQ9 sensor.
And built a linear and logarithmic dependence:
http://wiki.amperka.ru/_media/продукты:mq9:mq9_graph_factors.zip

**Comment by glundgren93** [comment]
Thank you!

**Comment by nomad605dis** [comment]
That's all right.
